services:
  - type: web
    runtime: node
    name: velix-backend
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeployTrigger: commit
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: TOKEN_EXPIRY
        sync: false
      - key: PORT
        sync: false
